[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200